name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          path: '../github_servers'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Deploy Server Code
        run: | 
          npm install
          npm run build:server
        working-directory: /home/ubuntu/github_servers
